

public enum StateDefinition
{
    LOADING,
    MAIN_MENU,
    CHARACTER_SELECT,
    ENVIRONMENT_SELECT,
    BATTLE_START,
    BATTLE_TURN_START,
    BATTLE_CHARACTER_TURN_START,
    BATTLE_WAIT_FOR_PLAYER_ACTION,
    BATTLE_WAIT_SELECT_TARGET,
    BATTLE_WAIT_FOR_AI_ACTION,
    BATTLE_EXECUTE_ACTION,
    BATTLE_CHARACTER_TURN_END,
    BATTLE_TURN_END,
    BATTLE_WON,
    BATTLE_LOSE,
    BATTLE_END
}
